# HTTP headers
webrick:
  headers:
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Content-Security-Policy: "default-src 'self'; img-src 'self' www.googletagmanager.com www.google-analytics.com cdn.jsdelivr.net ir-fr.amazon-adsystem.com; script-src 'self' 'unsafe-inline' www.googletagmanager.com www.google-analytics.com code.jquery.com cdn.jsdelivr.net cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net; frame-src www.youtube.com; font-src 'self' data: cdn.jsdelivr.net"

# Site settings
title: Sébastien Combéfis
email: sebastien@combefis.be
description: >
  The personal website of Sébastien Combéfis contains information about
  his research and teaching activities, and other personal information.
baseurl: ""
url: https://sebastien.combefis.be
enforce_ssl: sebastien.combefis.be
include: [".well-known"]
permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown

# Translation
t:
  en:
    teaching:
      name: Teaching
      url: /teaching
    research:
      name: Research
      url: /research
    politics:
      name: Politics
      url: /politics
    blog:
      name: Blog
      url: /blog
    about:
      name: About
      url: /about
  fr:
    teaching:
      name: Enseignement
      url: /fr/teaching
    research:
      name: Recherche
      url: /fr/research
    politics:
      name: Politique
      url: /fr/politics
    blog:
      name: Blog
      url: /fr/blog
    about:
      name: À propos
      url: /fr/about
